name: Fetch Entire S3 Bucket

on:
  workflow_dispatch:
   
jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch data from S3
        run: |
          aws s3 sync s3://cof-bucket/ .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: your-region  # Replace with your bucket's region
